[package]
name = "net-types-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
path = "../../upstream/net-types/src/macros.rs"
doctest = false

[dependencies]
assert_matches.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
